### ISSUE TITLE
magnet torrents not accepting UDP?

### ISSUE THREAD

**Issue by galileomd** [hadouken/hadouken#100]
System.ArgumentException: Only 'http' and 'https' schemes are allowed.
Parameter name: requestUri
   at System.Net.Http.HttpRequestMessage.InitializeValues(HttpMethod method, Uri requestUri)
   at System.Net.Http.HttpRequestMessage..ctor(HttpMethod method, Uri requestUri)
   at System.Net.Http.HttpClient.GetAsync(Uri requestUri, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetContentAsync[T](Uri requestUri, HttpCompletionOption completionOption, T defaultValue, Func`2 readAs)
   at System.Net.Http.HttpClient.GetByteArrayAsync(Uri requestUri)
   at Hadouken.Common.Net.HttpClientWrapper.GetByteArrayAsync(Uri uri)
   at Hadouken.Extensions.Rss.FeedChecker.Download(Filter filter, SyndicationItem item)
   at Hadouken.Extensions.Rss.FeedChecker.Check(Feed feed)
   at Hadouken.Extensions.Rss.RssPlugin.CheckFeeds()

**Comment by galileomd** [comment]
awesome, thanks for the quick fix!  really like the app, particularly the windows service aspect!
