### ISSUE TITLE
Daemon randomly? crashes

### ISSUE THREAD

**Issue by aniscartujo** [hadouken/hadouken#196]
I am running Hadouken 4.7 on Windows 2008 R2 64Bits and it randomly crashes... I don't know exactly how to force the error, but I only use it to seed big files (so it must be related)... And from time to time I got a error and the service stops. (Error grabbed from windows event log)

Application: Hadouken.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
Stack:
   at Nowin.SaeaLayerCallback.StartReceive(Byte[], Int32, Int32)
   at Nowin.Transport2HttpHandler.StartNextReceive()
   at Nowin.Transport2HttpHandler.FinishSend(System.Exception)
   at Nowin.SaeaLayerCallback.ProcessSend()
   at Nowin.SaeaLayerCallback.IoCompleted(System.Object, System.Net.Sockets.SocketAsyncEventArgs)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(System.Net.Sockets.SocketAsyncEventArgs)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(System.Net.Sockets.SocketError, Int32, System.Net.Sockets.SocketFlags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped_)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped_)

**Comment by vktr** [comment]
Any reason you're running v4.7? You might have better success with v5.2.

Either way, the stack trace shows an error in the HTTP server parts of Hadouken. I'm a bit out-of-the-loop on the Nowin stack, however I don't think it is related to seeding big files.
